"""Update EmailSettings for OAuth

Revision ID: 4b2c15e99f2e
Revises: 
Create Date: 2024-09-13 22:38:42.813595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2c15e99f2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_client_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('oauth_tenant_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('oauth_client_secret', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('oauth_scope', sa.String(length=150), nullable=True))
        batch_op.drop_column('email_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_password', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('oauth_scope')
        batch_op.drop_column('oauth_client_secret')
        batch_op.drop_column('oauth_tenant_id')
        batch_op.drop_column('oauth_client_id')

    # ### end Alembic commands ###
